// <auto-generated>
// This file was generated by Headsetsniper.Godot.FSharp.ShimGen (test shims).
// Do NOT edit this file manually. Any changes will be overwritten.
// ShimGenVersion: 1.0.0.0
// Source F# type: FSharp.Tests.TetrisGameFeatureTests
#nullable enable
// </auto-generated>
using System;
using System.Threading.Tasks;
using GdUnit4;

namespace GeneratedTests
{
    [TestSuite]
    public class TetrisGameFeatureTests_TestsShim
    {
        private FSharp.Tests.TetrisGameFeatureTests _impl = new FSharp.Tests.TetrisGameFeatureTests();
        [BeforeTest]
        public void Setup()
        {
            var __mi = _impl.GetType().GetMethod("Setup", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic); if  ( __mi == null ) throw  new  System . MissingMethodException ( _impl . GetType ( ) . FullName ,  "Setup" ) ;  __mi . Invoke ( _impl ,  System . Array . Empty < object ? > ( ) ) ; 
        }

        [AfterTest]
        public void Teardown()
        {
            var __mi = _impl.GetType().GetMethod("Teardown", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic); if  ( __mi == null ) throw  new  System . MissingMethodException ( _impl . GetType ( ) . FullName ,  "Teardown" ) ;  __mi . Invoke ( _impl ,  System . Array . Empty < object ? > ( ) ) ; 
        }

        [TestCase]
        public void Spawns_new_block_when_previous_locks()
        {
            var __mi = _impl.GetType().GetMethod("Spawns new block when previous locks", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic); if  ( __mi == null ) throw  new  System . MissingMethodException ( _impl . GetType ( ) . FullName ,  "Spawns new block when previous locks" ) ;  var  __task  =  ( System . Threading . Tasks . Task ) ( __mi . Invoke ( _impl ,  System . Array . Empty < object ? > ( ) ) ! ) ;  __task . GetAwaiter ( ) . GetResult ( ) ; 
        }

        [TestCase]
        public void Hard_drop_places_piece_on_bottom_then_locks_on_next_tick()
        {
            var __mi = _impl.GetType().GetMethod("Hard drop places piece on bottom then locks on next tick", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic); if  ( __mi == null ) throw  new  System . MissingMethodException ( _impl . GetType ( ) . FullName ,  "Hard drop places piece on bottom then locks on next tick" ) ;  var  __task  =  ( System . Threading . Tasks . Task ) ( __mi . Invoke ( _impl ,  System . Array . Empty < object ? > ( ) ) ! ) ;  __task . GetAwaiter ( ) . GetResult ( ) ; 
        }

        [TestCase]
        public void Bagging_stores_current_piece()
        {
            var __mi = _impl.GetType().GetMethod("Bagging stores current piece", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic); if  ( __mi == null ) throw  new  System . MissingMethodException ( _impl . GetType ( ) . FullName ,  "Bagging stores current piece" ) ;  var  __task  =  ( System . Threading . Tasks . Task ) ( __mi . Invoke ( _impl ,  System . Array . Empty < object ? > ( ) ) ! ) ;  __task . GetAwaiter ( ) . GetResult ( ) ; 
        }

        [TestCase]
        public void Restoring_retrieves_bagged_piece()
        {
            var __mi = _impl.GetType().GetMethod("Restoring retrieves bagged piece", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic); if  ( __mi == null ) throw  new  System . MissingMethodException ( _impl . GetType ( ) . FullName ,  "Restoring retrieves bagged piece" ) ;  var  __task  =  ( System . Threading . Tasks . Task ) ( __mi . Invoke ( _impl ,  System . Array . Empty < object ? > ( ) ) ! ) ;  __task . GetAwaiter ( ) . GetResult ( ) ; 
        }

        [TestCase]
        public void Clearing_a_line_increases_score_and_removes_row()
        {
            var __mi = _impl.GetType().GetMethod("Clearing a line increases score and removes row", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic); if  ( __mi == null ) throw  new  System . MissingMethodException ( _impl . GetType ( ) . FullName ,  "Clearing a line increases score and removes row" ) ;  var  __task  =  ( System . Threading . Tasks . Task ) ( __mi . Invoke ( _impl ,  System . Array . Empty < object ? > ( ) ) ! ) ;  __task . GetAwaiter ( ) . GetResult ( ) ; 
        }
    }
}