<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <RunSettingsFile>$(MSBuildProjectDirectory)\tests.runsettings</RunSettingsFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="NUnitLite" Version="3.14.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" />
  </ItemGroup>

  <PropertyGroup Condition="'$(UseNUnitLite)' == 'true'">
    <OutputType>Exe</OutputType>
    <StartupObject>ShimGen.Tests.Program</StartupObject>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>

  <ItemGroup>
  <ProjectReference Include="..\ShimGen\Headsetsniper.Godot.FSharp.ShimGen.csproj" />
  <ProjectReference Include="..\Annotations\Headsetsniper.Godot.FSharp.Annotations.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseNUnitLite)' != 'true'">
    <Compile Remove="Program.NUnitLite.cs" />
  </ItemGroup>
</Project>
