using System.Text;

namespace Headsetsniper.Godot.FSharp.ShimGen;

internal static partial class Program
{
    private static bool WriteIfChanged(string path, string content)
    {
        try
        {
            if (File.Exists(path))
            {
                var old = File.ReadAllText(path);
                if (!NeedsHeaderNormalization(old) && old == content)
                    return false;

                var oldHash = ExtractHash(old);
                var newHash = ExtractHash(content);
                var oldVer = ExtractShimGenVersion(old);
                var newVer = ExtractShimGenVersion(content);

                if (!string.IsNullOrEmpty(oldHash) && !string.IsNullOrEmpty(newHash) && string.Equals(oldHash, newHash, StringComparison.Ordinal))
                {
                    if (!IsOlderVersion(oldVer, newVer))
                        return false; // same source; keep user edits
                }
            }

            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            return true;
        }
        catch
        {
            return false;
        }
    }

    private static bool WouldWrite(string path, string content)
    {
        try
        {
            if (!File.Exists(path)) return true;
            var old = File.ReadAllText(path);
            if (!NeedsHeaderNormalization(old) && old == content) return false;

            var oldHash = ExtractHash(old);
            var newHash = ExtractHash(content);
            var oldVer = ExtractShimGenVersion(old);
            var newVer = ExtractShimGenVersion(content);
            if (!string.IsNullOrEmpty(oldHash) && !string.IsNullOrEmpty(newHash) && string.Equals(oldHash, newHash, StringComparison.Ordinal))
                return IsOlderVersion(oldVer, newVer);
            return true;
        }
        catch { return true; }
    }

    private static bool NeedsHeaderNormalization(string content)
        => content.Contains("\r\n");

    private static bool PathsEqual(string a, string b)
        => string.Equals(Path.GetFullPath(a).TrimEnd('\\', '/'), Path.GetFullPath(b).TrimEnd('\\', '/'), StringComparison.OrdinalIgnoreCase);

    private static void RemoveOtherGeneratedForSource(string outDir, string relFs, string keepPath, bool dryRun, List<string> plannedDeletes)
    {
        try
        {
            var dir = Path.GetFullPath(outDir);
            if (!Directory.Exists(dir)) return;
            foreach (var file in Directory.EnumerateFiles(dir, "*.cs", SearchOption.AllDirectories))
            {
                if (PathsEqual(file, keepPath)) continue;
                string text;
                try { text = File.ReadAllText(file); } catch { continue; }
                var srcRel = ExtractSourceFileRel(text);
                if (string.IsNullOrEmpty(srcRel)) continue;
                if (PathEqualsRel(srcRel!, relFs))
                {
                    plannedDeletes.Add(file);
                    if (!dryRun) { try { File.Delete(file); } catch { } }
                }
            }
        }
        catch { }
    }

    private static void PruneOrphans(string outDir, string fsDir, HashSet<string> liveTypes, bool dryRun, List<string> plannedDeletes)
    {
        try
        {
            var dir = Path.GetFullPath(outDir);
            if (!Directory.Exists(dir)) return;
            foreach (var file in Directory.EnumerateFiles(dir, "*.cs", SearchOption.AllDirectories))
            {
                string text;
                try { text = File.ReadAllText(file); } catch { continue; }
                if (!IsGeneratedHeader(text)) continue;
                var srcType = ExtractSourceTypeFullName(text);
                var srcRel = ExtractSourceFileRel(text);
                var hasSrc = !string.IsNullOrEmpty(srcRel) && File.Exists(Path.Combine(fsDir, srcRel!.Replace('/', Path.DirectorySeparatorChar)));
                var stillLive = !string.IsNullOrEmpty(srcType) && liveTypes.Contains(srcType!);
                if (!hasSrc || !stillLive)
                {
                    plannedDeletes.Add(file);
                    if (!dryRun) { try { File.Delete(file); } catch { } }
                }
            }
        }
        catch { }
    }

    private static bool IsGeneratedHeader(string content)
        => content.StartsWith("// <auto-generated>");

    private static bool IsGeneratedFile(string path)
    {
        try { var first = File.ReadLines(path).FirstOrDefault(); return first != null && first.StartsWith("// <auto-generated>"); }
        catch { return false; }
    }

    private static bool PathEqualsRel(string relA, string relB)
        => NormalizeRel(relA).Equals(NormalizeRel(relB), StringComparison.OrdinalIgnoreCase);

    private static string NormalizeRel(string rel)
        => rel.Replace('\\', '/').TrimStart('/');

    private static string? FindExistingGeneratedPath(string outDir, string className, string? sourceTypeFullName, string? currentHash)
    {
        try
        {
            var dir = Path.GetFullPath(outDir);
            if (!Directory.Exists(dir)) return null;

            string? Match(bool requireHash)
            {
                foreach (var file in Directory.EnumerateFiles(dir, className + ".cs", SearchOption.AllDirectories))
                {
                    string text; try { text = File.ReadAllText(file); } catch { continue; }
                    if (!IsGeneratedHeader(text)) continue;
                    var tfn = ExtractSourceTypeFullName(text);
                    if (!string.IsNullOrEmpty(sourceTypeFullName) && !string.Equals(tfn, sourceTypeFullName, StringComparison.Ordinal))
                        continue;
                    if (requireHash && !string.IsNullOrEmpty(currentHash))
                    {
                        var oldHash = ExtractHash(text);
                        if (!string.Equals(oldHash, currentHash, StringComparison.Ordinal))
                            continue;
                    }
                    return file;
                }
                return null;
            }

            // First try strict (hash) match. If that fails, fall back to any prior generated file for this class+type.
            return Match(requireHash: true) ?? Match(requireHash: false);
        }
        catch { return null; }
    }

    private static (string? rel, string? hash) TryGetSourceInfo(string dir, Type type)
    {
        var src = FindFsSourceForType(dir, type);
        if (string.IsNullOrEmpty(src)) return (null, null);
        var rel = Path.GetRelativePath(dir, src!).Replace('\\', '/');
        var hash = ComputeFileHash(src!);
        return (rel, hash);
    }

    private static string? FindFsSourceForType(string dir, Type type)
    {
        try
        {
            var files = Directory.EnumerateFiles(dir, "*.fs", SearchOption.AllDirectories).ToArray();
            if (files.Length == 0) return null;
            var typeName = type.Name;
            var ns = type.Namespace ?? string.Empty;
            int Score(string content)
            {
                int score = 0;
                if (!string.IsNullOrEmpty(ns) && content.IndexOf("namespace " + ns, StringComparison.Ordinal) >= 0)
                    score += 2;
                if (System.Text.RegularExpressions.Regex.IsMatch(content, @"(^|\s)type\s+" + System.Text.RegularExpressions.Regex.Escape(typeName) + @"(\b|\s)", System.Text.RegularExpressions.RegexOptions.Multiline))
                    score += 5;
                if (content.Contains("GodotScript", StringComparison.Ordinal)) score += 1;
                return score;
            }
            string? best = null; int bestScore = int.MinValue;
            foreach (var f in files)
            {
                string content; try { content = File.ReadAllText(f); } catch { continue; }
                var s = Score(content);
                if (s > bestScore) { bestScore = s; best = f; }
            }
            return bestScore >= 3 ? best : null;
        }
        catch { return null; }
    }

    private static string ComputeFileHash(string path)
    {
        try
        {
            using var sha = System.Security.Cryptography.SHA256.Create();
            using var fs = File.OpenRead(path);
            var hash = sha.ComputeHash(fs);
            return Convert.ToHexString(hash).ToLowerInvariant();
        }
        catch { return string.Empty; }
    }
}
