using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Headsetsniper.Godot.FSharp.ShimGen;

internal static partial class RoslynCodeGenerator
{
    private sealed record GenContext(ScriptSpec Spec, string? FsSourceDir);

    public static string Generate(ScriptSpec spec, string? fsSourceDir)
    {
        var ctx = new GenContext(spec, fsSourceDir);
        var header = BuildHeader(ctx);
        var usings = BuildUsings();
        var nsDecl = CreateNamespace();
        var classDecl = CreateClass(ctx);
        classDecl = classDecl.AddMembers(CreateImplField(ctx));
        classDecl = classDecl.AddMembers(CreateExportMembers(ctx).ToArray());
        classDecl = classDecl.AddMembers(CreateLifecycleAndReadyMembers(ctx).ToArray());
        classDecl = classDecl.AddMembers(CreateUiAndCanvasMembers(ctx).ToArray());
        classDecl = classDecl.AddMembers(CreateSignalMembers(ctx).ToArray());
        nsDecl = nsDecl.AddMembers(classDecl);
        var cu = SyntaxFactory.CompilationUnit()
            .WithUsings(SyntaxFactory.List(usings))
            .AddMembers(nsDecl)
            .WithLeadingTrivia(header);
        var text = cu.NormalizeWhitespace().ToFullString();
        return text.Replace("\r\n", "\n");
    }

    private static SyntaxTriviaList BuildHeader(GenContext ctx)
    {
        var spec = ctx.Spec;
        var version = GetGeneratorVersionMajorMinorPatch();
        var headerLines = new List<SyntaxTrivia>
        {
            SyntaxFactory.Comment("// <auto-generated>"), SyntaxFactory.EndOfLine("\n"),
            SyntaxFactory.Comment("// This file was generated by Headsetsniper.Godot.FSharp.ShimGen."), SyntaxFactory.EndOfLine("\n"),
            SyntaxFactory.Comment("// Do NOT edit this file manually. Any changes will be overwritten."), SyntaxFactory.EndOfLine("\n"),
            SyntaxFactory.Comment("// ShimGenVersion: " + version), SyntaxFactory.EndOfLine("\n"),
            SyntaxFactory.Comment("// Source F# type: " + (spec.ImplType.FullName ?? spec.ImplType.Name ?? "GeneratedShim")), SyntaxFactory.EndOfLine("\n")
        };
        if (!string.IsNullOrEmpty(ctx.FsSourceDir))
        {
            var (rel, hash) = TryGetSourceInfo(ctx.FsSourceDir!, spec.ImplType);
            if (!string.IsNullOrEmpty(rel))
            {
                headerLines.Add(SyntaxFactory.Comment("// SourceFile: " + rel));
                headerLines.Add(SyntaxFactory.EndOfLine("\n"));
                if (!string.IsNullOrEmpty(hash))
                {
                    headerLines.Add(SyntaxFactory.Comment("// SourceHash: " + hash));
                    headerLines.Add(SyntaxFactory.EndOfLine("\n"));
                }
            }
        }
        headerLines.Add(SyntaxFactory.Comment("// </auto-generated>"));
        headerLines.Add(SyntaxFactory.EndOfLine("\n"));
        headerLines.Add(SyntaxFactory.EndOfLine("\n"));
        return SyntaxFactory.TriviaList(headerLines);
    }

    private static UsingDirectiveSyntax[] BuildUsings() => new[]
    {
        SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("Godot")),
        SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("Headsetsniper.Godot.FSharp.Annotations"))
    };

    private static NamespaceDeclarationSyntax CreateNamespace()
        => SyntaxFactory.NamespaceDeclaration(SyntaxFactory.IdentifierName("Generated"))
            .WithNamespaceKeyword(SyntaxFactory.Token(default, SyntaxKind.NamespaceKeyword, "namespace", "namespace", default))
            .NormalizeWhitespace();

    private static ClassDeclarationSyntax CreateClass(GenContext ctx)
    {
        var spec = ctx.Spec;
        var attrLists = new List<AttributeListSyntax>();
        if (spec.Tool)
            attrLists.Add(SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(SyntaxFactory.Attribute(SyntaxFactory.IdentifierName("Tool")))));
        attrLists.Add(SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(SyntaxFactory.Attribute(SyntaxFactory.IdentifierName("GlobalClass")))));
        if (!string.IsNullOrWhiteSpace(spec.Icon))
        {
            var iconAttr = SyntaxFactory.Attribute(SyntaxFactory.IdentifierName("Icon"))
                .WithArgumentList(SyntaxFactory.AttributeArgumentList(SyntaxFactory.SingletonSeparatedList(SyntaxFactory.AttributeArgument(SyntaxFactory.LiteralExpression(SyntaxKind.StringLiteralExpression, SyntaxFactory.Literal(spec.Icon))))));
            attrLists.Add(SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(iconAttr)));
        }
        return SyntaxFactory.ClassDeclaration(spec.ClassName)
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword), SyntaxFactory.Token(SyntaxKind.PartialKeyword))
            .WithAttributeLists(SyntaxFactory.List(attrLists))
            .WithBaseList(SyntaxFactory.BaseList(SyntaxFactory.SingletonSeparatedList<BaseTypeSyntax>(SyntaxFactory.SimpleBaseType(SyntaxFactory.ParseTypeName(spec.BaseTypeName)))));
    }

    private static MemberDeclarationSyntax CreateImplField(GenContext ctx)
    {
        var spec = ctx.Spec;
        var implTypeName = SyntaxFactory.ParseTypeName(GetTypeDisplayName(spec.ImplType));
        return SyntaxFactory.FieldDeclaration(
                SyntaxFactory.VariableDeclaration(implTypeName)
                    .WithVariables(SyntaxFactory.SingletonSeparatedList(SyntaxFactory.VariableDeclarator(SyntaxFactory.Identifier("_impl")).WithInitializer(SyntaxFactory.EqualsValueClause(SyntaxFactory.ObjectCreationExpression(implTypeName).WithArgumentList(SyntaxFactory.ArgumentList()))))))
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PrivateKeyword), SyntaxFactory.Token(SyntaxKind.ReadOnlyKeyword));
    }

    private static IEnumerable<MemberDeclarationSyntax> CreateExportMembers(GenContext ctx)
        => ctx.Spec.Exports
            .Select(p => BuildExportPropertyMember(ctx.Spec, p))
            .Where(md => md is not null)!;

    private static IEnumerable<MemberDeclarationSyntax> CreateLifecycleAndReadyMembers(GenContext ctx)
        => BuildLifecycleAndReadyMembers(ctx.Spec);

    private static IEnumerable<MemberDeclarationSyntax> CreateUiAndCanvasMembers(GenContext ctx)
        => BuildUiAndCanvasMembers(ctx.Spec);

    private static IEnumerable<MemberDeclarationSyntax> CreateSignalMembers(GenContext ctx)
        => BuildSignalMembers(ctx.Spec);

    private static string GetGeneratorVersionMajorMinorPatch()
    {
        try
        {
            var asm = typeof(RoslynCodeGenerator).Assembly;
            var info = asm.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
            var raw = !string.IsNullOrWhiteSpace(info) ? info! : (asm.GetName().Version?.ToString() ?? "0.0.0");
            var core = raw.Split('-', '+')[0].Trim();
            var parts = core.Split('.');
            if (parts.Length >= 3)
                return string.Join('.', parts[0], parts[1], parts[2]);
            if (parts.Length == 2)
                return string.Join('.', parts[0], parts[1], "0");
            if (parts.Length == 1)
                return string.Join('.', parts[0], "0", "0");
            return "0.0.0";
        }
        catch { return "0.0.0"; }
    }

    private static string GetTypeDisplayName(Type t)
    {
        if (t.IsArray)
        {
            var elem = t.GetElementType()!;
            return GetTypeDisplayName(elem) + "[]";
        }
        if (t.IsGenericType)
        {
            var def = t.GetGenericTypeDefinition();
            var ns = def.Namespace;
            var name = def.Name;
            var backtick = name.IndexOf('`');
            if (backtick >= 0) name = name.Substring(0, backtick);
            var args = t.GetGenericArguments().Select(GetTypeDisplayName);
            var prefix = string.IsNullOrEmpty(ns) ? string.Empty : ns + ".";
            return prefix + name + "<" + string.Join(", ", args) + ">";
        }
        if (t.IsNested)
        {
            var parts = new List<string>();
            var cur = t;
            while (cur != null)
            {
                parts.Add(cur.Name);
                cur = cur.DeclaringType;
            }
            parts.Reverse();
            var ns = t.Namespace;
            var prefix = string.IsNullOrEmpty(ns) ? string.Empty : ns + ".";
            return prefix + string.Join(".", parts);
        }
        return t.FullName ?? t.Name ?? "System.Object";
    }

    private static (string? rel, string? hash) TryGetSourceInfo(string dir, Type type)
    {
        var src = FindFsSourceForType(dir, type);
        if (string.IsNullOrEmpty(src)) return (null, null);
        var rel = Path.GetRelativePath(dir, src!).Replace('\\', '/');
        var hash = ComputeFileHash(src!);
        return (rel, hash);
    }

    private static string? FindFsSourceForType(string dir, Type type)
    {
        try
        {
            var files = Directory.EnumerateFiles(dir, "*.fs", SearchOption.AllDirectories).ToArray();
            if (files.Length == 0) return null;
            var typeName = type.Name;
            var ns = type.Namespace ?? string.Empty;
            int Score(string content)
            {
                int score = 0;
                if (!string.IsNullOrEmpty(ns) && content.IndexOf("namespace " + ns, StringComparison.Ordinal) >= 0)
                    score += 2;
                if (System.Text.RegularExpressions.Regex.IsMatch(content, @"(^|\s)type\s+" + System.Text.RegularExpressions.Regex.Escape(typeName) + @"(\b|\s)", System.Text.RegularExpressions.RegexOptions.Multiline))
                    score += 5;
                if (content.Contains("GodotScript", StringComparison.Ordinal)) score += 1;
                return score;
            }
            string? best = null; int bestScore = int.MinValue;
            foreach (var f in files)
            {
                string content; try { content = File.ReadAllText(f); } catch { continue; }
                var s = Score(content);
                if (s > bestScore) { bestScore = s; best = f; }
            }
            return bestScore >= 3 ? best : null;
        }
        catch { return null; }
    }

    private static string ComputeFileHash(string path)
    {
        try
        {
            using var sha = System.Security.Cryptography.SHA256.Create();
            using var fs = File.OpenRead(path);
            var hash = sha.ComputeHash(fs);
            return Convert.ToHexString(hash).ToLowerInvariant();
        }
        catch { return string.Empty; }
    }

    private static (bool isOption, Type? inner) TryUnwrapFSharpOption(Type t)
    {
        try
        {
            if (t.IsGenericType && t.GetGenericTypeDefinition().FullName is string gdef &&
                (gdef == "Microsoft.FSharp.Core.FSharpOption`1" || gdef == "FSharpOption`1"))
            {
                var ga = t.GetGenericArguments();
                if (ga.Length == 1) return (true, ga[0]);
            }
        }
        catch { }
        return (false, null);
    }

    private static bool IsSubclassOfByName(Type t, string baseFullName)
    {
        try
        {
            var cur = t;
            while (cur != null)
            {
                if (cur.FullName == baseFullName) return true;
                cur = cur.BaseType;
            }
        }
        catch { }
        return false;
    }

    private static string Escape(string s)
        => string.IsNullOrEmpty(s) ? string.Empty : s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
