using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Headsetsniper.Godot.FSharp.ShimGen;

internal static class RoslynCodeGenerator
{
    private sealed record GenContext(ScriptSpec Spec, string? FsSourceDir);

    public static string Generate(ScriptSpec spec, string? fsSourceDir)
    {
        var ctx = new GenContext(spec, fsSourceDir);

        // 1) Header and usings
        var header = BuildHeader(ctx);
        var usings = BuildUsings();

        // 2) Namespace + class shell
        var nsDecl = CreateNamespace();
        var classDecl = CreateClass(ctx);

        // 3) Members in pipeline order: field -> exports -> lifecycle -> UI -> signals
        classDecl = classDecl.AddMembers(CreateImplField(ctx));
        classDecl = classDecl.AddMembers(CreateExportMembers(ctx).ToArray());
        classDecl = classDecl.AddMembers(CreateLifecycleAndReadyMembers(ctx).ToArray());
        classDecl = classDecl.AddMembers(CreateUiAndCanvasMembers(ctx).ToArray());
        classDecl = classDecl.AddMembers(CreateSignalMembers(ctx).ToArray());

        // 4) Compose CU
        nsDecl = nsDecl.AddMembers(classDecl);
        var cu = SyntaxFactory.CompilationUnit()
            .WithUsings(SyntaxFactory.List(usings))
            .AddMembers(nsDecl)
            .WithLeadingTrivia(header);

        // 5) Deterministic text
        var text = cu.NormalizeWhitespace().ToFullString();
        return text.Replace("\r\n", "\n");
    }

    private static SyntaxTriviaList BuildHeader(GenContext ctx)
    {
        var spec = ctx.Spec;
        var version = GetGeneratorVersionMajorMinorPatch();
        var headerLines = new List<SyntaxTrivia>
        {
            SyntaxFactory.Comment("// <auto-generated>"), SyntaxFactory.EndOfLine("\n"),
            SyntaxFactory.Comment("// This file was generated by Headsetsniper.Godot.FSharp.ShimGen."), SyntaxFactory.EndOfLine("\n"),
            SyntaxFactory.Comment("// Do NOT edit this file manually. Any changes will be overwritten."), SyntaxFactory.EndOfLine("\n"),
            SyntaxFactory.Comment("// ShimGenVersion: " + version), SyntaxFactory.EndOfLine("\n"),
            SyntaxFactory.Comment("// Source F# type: " + (spec.ImplType.FullName ?? spec.ImplType.Name ?? "GeneratedShim")), SyntaxFactory.EndOfLine("\n")
        };
        if (!string.IsNullOrEmpty(ctx.FsSourceDir))
        {
            var (rel, hash) = TryGetSourceInfo(ctx.FsSourceDir!, spec.ImplType);
            if (!string.IsNullOrEmpty(rel))
            {
                headerLines.Add(SyntaxFactory.Comment("// SourceFile: " + rel));
                headerLines.Add(SyntaxFactory.EndOfLine("\n"));
                if (!string.IsNullOrEmpty(hash))
                {
                    headerLines.Add(SyntaxFactory.Comment("// SourceHash: " + hash));
                    headerLines.Add(SyntaxFactory.EndOfLine("\n"));
                }
            }
        }
        headerLines.Add(SyntaxFactory.Comment("// </auto-generated>"));
        headerLines.Add(SyntaxFactory.EndOfLine("\n"));
        headerLines.Add(SyntaxFactory.EndOfLine("\n"));
        return SyntaxFactory.TriviaList(headerLines);
    }

    private static UsingDirectiveSyntax[] BuildUsings() => new[]
    {
        SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("Godot")),
        SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("Headsetsniper.Godot.FSharp.Annotations"))
    };

    private static NamespaceDeclarationSyntax CreateNamespace()
        => SyntaxFactory.NamespaceDeclaration(SyntaxFactory.IdentifierName("Generated"))
            .WithNamespaceKeyword(SyntaxFactory.Token(default, SyntaxKind.NamespaceKeyword, "namespace", "namespace", default))
            .NormalizeWhitespace();

    private static ClassDeclarationSyntax CreateClass(GenContext ctx)
    {
        var spec = ctx.Spec;
        var attrLists = new List<AttributeListSyntax>();
        if (spec.Tool)
            attrLists.Add(SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(SyntaxFactory.Attribute(SyntaxFactory.IdentifierName("Tool")))));
        attrLists.Add(SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(SyntaxFactory.Attribute(SyntaxFactory.IdentifierName("GlobalClass")))));
        if (!string.IsNullOrWhiteSpace(spec.Icon))
        {
            var iconAttr = SyntaxFactory.Attribute(SyntaxFactory.IdentifierName("Icon"))
                .WithArgumentList(SyntaxFactory.AttributeArgumentList(SyntaxFactory.SingletonSeparatedList(SyntaxFactory.AttributeArgument(SyntaxFactory.LiteralExpression(SyntaxKind.StringLiteralExpression, SyntaxFactory.Literal(spec.Icon))))));
            attrLists.Add(SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(iconAttr)));
        }
        return SyntaxFactory.ClassDeclaration(spec.ClassName)
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword), SyntaxFactory.Token(SyntaxKind.PartialKeyword))
            .WithAttributeLists(SyntaxFactory.List(attrLists))
            .WithBaseList(SyntaxFactory.BaseList(SyntaxFactory.SingletonSeparatedList<BaseTypeSyntax>(SyntaxFactory.SimpleBaseType(SyntaxFactory.ParseTypeName(spec.BaseTypeName)))));
    }

    private static MemberDeclarationSyntax CreateImplField(GenContext ctx)
    {
        var spec = ctx.Spec;
        var implTypeName = SyntaxFactory.ParseTypeName(GetTypeDisplayName(spec.ImplType));
        return SyntaxFactory.FieldDeclaration(
                SyntaxFactory.VariableDeclaration(implTypeName)
                    .WithVariables(SyntaxFactory.SingletonSeparatedList(SyntaxFactory.VariableDeclarator(SyntaxFactory.Identifier("_impl")).WithInitializer(SyntaxFactory.EqualsValueClause(SyntaxFactory.ObjectCreationExpression(implTypeName).WithArgumentList(SyntaxFactory.ArgumentList()))))))
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PrivateKeyword), SyntaxFactory.Token(SyntaxKind.ReadOnlyKeyword));
    }

    private static IEnumerable<MemberDeclarationSyntax> CreateExportMembers(GenContext ctx)
        => ctx.Spec.Exports
            .Select(p => BuildExportProperty(ctx.Spec, p))
            .Where(code => !string.IsNullOrEmpty(code))
            .Select(code => SyntaxFactory.ParseMemberDeclaration(code!)!)
            .Where(md => md is not null)!;

    private static IEnumerable<MemberDeclarationSyntax> CreateLifecycleAndReadyMembers(GenContext ctx)
        => BuildLifecycleAndReadyMembers(ctx.Spec)
            .Select(code => SyntaxFactory.ParseMemberDeclaration(code)!)
            .Where(md => md is not null)!;

    private static IEnumerable<MemberDeclarationSyntax> CreateUiAndCanvasMembers(GenContext ctx)
        => BuildUiAndCanvasMembers(ctx.Spec)
            .Select(code => SyntaxFactory.ParseMemberDeclaration(code)!)
            .Where(md => md is not null)!;

    private static IEnumerable<MemberDeclarationSyntax> CreateSignalMembers(GenContext ctx)
        => BuildSignalMembers(ctx.Spec)
            .Select(code => SyntaxFactory.ParseMemberDeclaration(code)!)
            .Where(md => md is not null)!;

    private static string GetGeneratorVersionMajorMinorPatch()
    {
        try
        {
            var asm = typeof(RoslynCodeGenerator).Assembly;
            var info = asm.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
            var raw = !string.IsNullOrWhiteSpace(info) ? info! : (asm.GetName().Version?.ToString() ?? "0.0.0");
            var core = raw.Split('-', '+')[0].Trim();
            var parts = core.Split('.');
            if (parts.Length >= 3)
                return string.Join('.', parts[0], parts[1], parts[2]);
            if (parts.Length == 2)
                return string.Join('.', parts[0], parts[1], "0");
            if (parts.Length == 1)
                return string.Join('.', parts[0], "0", "0");
            return "0.0.0";
        }
        catch { return "0.0.0"; }
    }

    private static string GetTypeDisplayName(Type t)
    {
        if (t.IsArray)
        {
            var elem = t.GetElementType()!;
            return GetTypeDisplayName(elem) + "[]";
        }
        if (t.IsGenericType)
        {
            var def = t.GetGenericTypeDefinition();
            var ns = def.Namespace;
            var name = def.Name;
            var backtick = name.IndexOf('`');
            if (backtick >= 0) name = name.Substring(0, backtick);
            var args = t.GetGenericArguments().Select(GetTypeDisplayName);
            var prefix = string.IsNullOrEmpty(ns) ? string.Empty : ns + ".";
            return prefix + name + "<" + string.Join(", ", args) + ">";
        }
        if (t.IsNested)
        {
            var parts = new List<string>();
            var cur = t;
            while (cur != null)
            {
                parts.Add(cur.Name);
                cur = cur.DeclaringType;
            }
            parts.Reverse();
            var ns = t.Namespace;
            var prefix = string.IsNullOrEmpty(ns) ? string.Empty : ns + ".";
            return prefix + string.Join(".", parts);
        }
        return t.FullName ?? t.Name ?? "System.Object";
    }

    // Helpers for parity features
    private static (string? rel, string? hash) TryGetSourceInfo(string dir, Type type)
    {
        var src = FindFsSourceForType(dir, type);
        if (string.IsNullOrEmpty(src)) return (null, null);
        var rel = Path.GetRelativePath(dir, src!).Replace('\\', '/');
        var hash = ComputeFileHash(src!);
        return (rel, hash);
    }

    private static string? FindFsSourceForType(string dir, Type type)
    {
        try
        {
            var files = Directory.EnumerateFiles(dir, "*.fs", SearchOption.AllDirectories).ToArray();
            if (files.Length == 0) return null;
            var typeName = type.Name;
            var ns = type.Namespace ?? string.Empty;
            int Score(string content)
            {
                int score = 0;
                if (!string.IsNullOrEmpty(ns) && content.IndexOf("namespace " + ns, StringComparison.Ordinal) >= 0)
                    score += 2;
                if (System.Text.RegularExpressions.Regex.IsMatch(content, @"(^|\s)type\s+" + System.Text.RegularExpressions.Regex.Escape(typeName) + @"(\b|\s)", System.Text.RegularExpressions.RegexOptions.Multiline))
                    score += 5;
                if (content.Contains("GodotScript", StringComparison.Ordinal)) score += 1;
                return score;
            }
            string? best = null; int bestScore = int.MinValue;
            foreach (var f in files)
            {
                string content; try { content = File.ReadAllText(f); } catch { continue; }
                var s = Score(content);
                if (s > bestScore) { bestScore = s; best = f; }
            }
            return bestScore >= 3 ? best : null;
        }
        catch { return null; }
    }

    private static string ComputeFileHash(string path)
    {
        try
        {
            using var sha = System.Security.Cryptography.SHA256.Create();
            using var fs = File.OpenRead(path);
            var hash = sha.ComputeHash(fs);
            return Convert.ToHexString(hash).ToLowerInvariant();
        }
        catch { return string.Empty; }
    }

    private static (bool isOption, Type? inner) TryUnwrapFSharpOption(Type t)
    {
        try
        {
            if (t.IsGenericType && t.GetGenericTypeDefinition().FullName is string gdef &&
                (gdef == "Microsoft.FSharp.Core.FSharpOption`1" || gdef == "FSharpOption`1"))
            {
                var ga = t.GetGenericArguments();
                if (ga.Length == 1) return (true, ga[0]);
            }
        }
        catch { }
        return (false, null);
    }

    private static bool IsSubclassOfByName(Type t, string baseFullName)
    {
        try
        {
            var cur = t;
            while (cur != null)
            {
                if (cur.FullName == baseFullName) return true;
                cur = cur.BaseType;
            }
        }
        catch { }
        return false;
    }

    private static string Escape(string s)
        => string.IsNullOrEmpty(s) ? string.Empty : s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string BuildExportProperty(ScriptSpec spec, System.Reflection.PropertyInfo p)
    {
        var (isOpt, optInner) = TryUnwrapFSharpOption(p.PropertyType);
        var exportTypeName = GetTypeDisplayName(isOpt ? optInner! : p.PropertyType);
        string ValueGet() => isOpt ? $"_impl.{p.Name} is null ? default : _impl.{p.Name}.Value" : $"_impl.{p.Name}";
        string ValueSet() => isOpt ? $"_impl.{p.Name} = Microsoft.FSharp.Core.FSharpOption<{GetTypeDisplayName(optInner!)}>.Some(value)" : $"_impl.{p.Name} = value";

        var lines = new List<string>();

        void Add(string s) => lines.Add(s);
        IEnumerable<CustomAttributeData> Attrs() => p.GetCustomAttributesData();
        CustomAttributeData? GetAttr(string fullName) => Attrs().FirstOrDefault(a => a.AttributeType.FullName == fullName);
        bool HasAttr(string fullName) => Attrs().Any(a => a.AttributeType.FullName == fullName);

        // Run the small steps in order; short-circuit on first match
        if (TryEmitRange()) return Join();
        if (TryEmitFile()) return Join();
        if (TryEmitDir()) return Join();
        if (TryEmitResourceType()) return Join();
        if (TryEmitStringHints()) return Join();
        if (TryEmitColorNoAlpha()) return Join();
        if (TryEmitLayerMask2D()) return Join();
        if (TryEmitFlagsEnum()) return Join();

        void EmitPreAttributes()
        {
            var cat = GetAttr(Headsetsniper.Godot.FSharp.Annotations.Known.Types.ExportCategoryAttribute);
            if (cat is not null)
            {
                var name = cat.ConstructorArguments.Count > 0 ? (cat.ConstructorArguments[0].Value as string ?? string.Empty) : string.Empty;
                Add($"[ExportCategory(\"{Escape(name)}\")] ");
            }
            var sub = GetAttr(Headsetsniper.Godot.FSharp.Annotations.Known.Types.ExportSubgroupAttribute);
            if (sub is not null)
            {
                var name = sub.ConstructorArguments.Count > 0 ? (sub.ConstructorArguments[0].Value as string ?? string.Empty) : string.Empty;
                var prefix = sub.NamedArguments.FirstOrDefault(na => na.MemberName == "Prefix").TypedValue.Value as string;
                if (!string.IsNullOrEmpty(prefix)) Add($"[ExportSubgroup(\"{Escape(name)}\", Prefix=\"{Escape(prefix!)}\")] ");
                else Add($"[ExportSubgroup(\"{Escape(name)}\")] ");
            }
            var tip = GetAttr(Headsetsniper.Godot.FSharp.Annotations.Known.Types.ExportTooltipAttribute);
            if (tip is not null)
            {
                var text = tip.ConstructorArguments.Count > 0 ? (tip.ConstructorArguments[0].Value as string ?? string.Empty) : string.Empty;
                Add($"[ExportTooltip(\"{Escape(text)}\")] ");
            }
        }

        void EmitProperty(string exportAttr)
        {
            EmitPreAttributes();
            Add(exportAttr);
            Add($"public {exportTypeName} {p.Name} {{ get => {ValueGet()}; set => {ValueSet()}; }}");
        }

        string Join() => string.Join('\n', lines);

        bool TryEmitRange()
        {
            var rangeAttr = GetAttr(Headsetsniper.Godot.FSharp.Annotations.Known.Types.ExportRangeAttribute);
            if (rangeAttr is null) return false;
            double min = 0, max = 0, step = 0; bool slider = false;
            var ctor = rangeAttr.ConstructorArguments;
            if (ctor.Count >= 1) min = Convert.ToDouble(ctor[0].Value);
            if (ctor.Count >= 2) max = Convert.ToDouble(ctor[1].Value);
            if (ctor.Count >= 3) step = Convert.ToDouble(ctor[2].Value);
            if (ctor.Count >= 4 && ctor[3].ArgumentType == typeof(bool)) slider = (bool)ctor[3].Value!;
            EmitProperty($"[Export(PropertyHint.Range, \"{min},{max},{step},{(slider ? 1 : 0)}\")] ");
            return true;
        }

        bool TryEmitFile()
        {
            var fileAttr = GetAttr(Headsetsniper.Godot.FSharp.Annotations.Known.Types.ExportFileAttribute);
            if (fileAttr is null) return false;
            var filter = fileAttr.ConstructorArguments.Count > 0
                ? (fileAttr.ConstructorArguments[0].Value as string ?? string.Empty)
                : (fileAttr.NamedArguments.FirstOrDefault(na => na.MemberName == "Filter").TypedValue.Value as string ?? string.Empty);
            EmitProperty($"[Export(PropertyHint.File, \"{Escape(filter)}\")] ");
            return true;
        }

        bool TryEmitDir()
        {
            if (!HasAttr(Headsetsniper.Godot.FSharp.Annotations.Known.Types.ExportDirAttribute)) return false;
            EmitProperty("[Export(PropertyHint.Dir)] ");
            return true;
        }

        bool TryEmitResourceType()
        {
            var resAttr = GetAttr(Headsetsniper.Godot.FSharp.Annotations.Known.Types.ExportResourceTypeAttribute);
            if (resAttr is null) return false;
            var typeName = resAttr.ConstructorArguments.Count > 0 ? (resAttr.ConstructorArguments[0].Value as string ?? string.Empty) : string.Empty;
            EmitProperty($"[Export(PropertyHint.ResourceType, \"{Escape(typeName)}\")] ");
            return true;
        }

        bool TryEmitStringHints()
        {
            if (p.PropertyType != typeof(string)) return false;
            if (HasAttr(Headsetsniper.Godot.FSharp.Annotations.Known.Types.ExportMultilineAttribute))
            {
                EmitProperty("[Export(PropertyHint.MultilineText)] ");
                return true;
            }
            var enumList = GetAttr(Headsetsniper.Godot.FSharp.Annotations.Known.Types.ExportEnumListAttribute);
            if (enumList is not null)
            {
                var values = enumList.ConstructorArguments.Count > 0 ? (enumList.ConstructorArguments[0].Value as string ?? string.Empty) : string.Empty;
                EmitProperty($"[Export(PropertyHint.Enum, \"{Escape(values)}\")] ");
                return true;
            }
            return false;
        }

        bool TryEmitColorNoAlpha()
        {
            if (p.PropertyType.FullName != KnownGodot.Color) return false;
            if (!HasAttr(Headsetsniper.Godot.FSharp.Annotations.Known.Types.ExportColorNoAlphaAttribute)) return false;
            EmitProperty("[Export(PropertyHint.ColorNoAlpha)] ");
            return true;
        }

        bool TryEmitLayerMask2D()
        {
            if (!HasAttr(Headsetsniper.Godot.FSharp.Annotations.Known.Types.ExportLayerMask2DRenderAttribute)) return false;
            EmitProperty("[Export(PropertyHint.Layers2DRender)] ");
            return true;
        }

        bool TryEmitFlagsEnum()
        {
            if (!p.PropertyType.IsEnum) return false;
            if (!p.PropertyType.GetCustomAttributesData().Any(a => a.AttributeType.FullName == "System.FlagsAttribute")) return false;
            string hintList = string.Join(',', Enum.GetNames(p.PropertyType));
            EmitProperty($"[Export(PropertyHint.Flags, \"{hintList}\")] ");
            return true;
        }


        // Default export
        EmitProperty("[Export] ");
        return Join();
    }

    private static IEnumerable<string> BuildLifecycleAndReadyMembers(ScriptSpec spec)
    {
        var list = new List<string>();
        if (spec.HasEnterTree) list.Add("public override void _EnterTree() => _impl.EnterTree();");

        if (spec.HasReady)
        {
            var sb = new System.Text.StringBuilder();
            var shimDisplayLiteral = Escape(spec.ClassName);
            var implDisplayLiteral = Escape(spec.ImplType.FullName ?? spec.ImplType.Name ?? spec.ClassName);
            sb.AppendLine("public override void _Ready()");
            sb.AppendLine("{");
            sb.AppendLine($"    if (_impl is IGdScript<{spec.BaseTypeName}> gd)");
            sb.AppendLine("        gd.Node = this;");
            // NodePath wiring
            if (spec.NodePathMembers.Length > 0)
            {
                foreach (var np in spec.NodePathMembers)
                {
                    var pathExpr = string.IsNullOrEmpty(np.Path) ? $"nameof({np.Name})" : $"\"{Escape(np.Path!)}\"";
                    sb.AppendLine($"    var __n_{np.Name} = GetNodeOrNull<{GetTypeDisplayName(np.MemberType)}>(new NodePath({pathExpr}));");
                    if (np.IsOption)
                    {
                        sb.AppendLine($"    _impl.{np.Name} = __n_{np.Name} == null ? Microsoft.FSharp.Core.FSharpOption<{GetTypeDisplayName(np.MemberType)}>.None : Microsoft.FSharp.Core.FSharpOption<{GetTypeDisplayName(np.MemberType)}>.Some(__n_{np.Name});");
                    }
                    else
                    {
                        sb.AppendLine($"    if (__n_{np.Name} == null) throw new System.InvalidOperationException(\"[shimgen][{shimDisplayLiteral}] Missing required NodePath for {np.Name} on {implDisplayLiteral}\");");
                        sb.AppendLine($"    _impl.{np.Name} = __n_{np.Name};");
                    }
                }
            }
            if (spec.PreloadMembers.Length > 0)
            {
                foreach (var pl in spec.PreloadMembers)
                {
                    var sanitizedPath = Escape(pl.Path ?? string.Empty);
                    var memberNameLiteral = Escape(pl.Name);
                    var memberKind = pl.IsProperty ? "property" : "field";
                    var loadVar = $"__p_{pl.Name}";
                    sb.AppendLine($"    var {loadVar} = ResourceLoader.Load<{GetTypeDisplayName(pl.MemberType)}>(\"{sanitizedPath}\");");
                    sb.AppendLine($"    if ({loadVar} == null) throw new System.InvalidOperationException(\"[shimgen][{shimDisplayLiteral}] Missing preload resource \\\"{sanitizedPath}\\\" for {memberKind} \\\"{memberNameLiteral}\\\" on {implDisplayLiteral}\");");
                    if (pl.IsOption)
                        sb.AppendLine($"    _impl.{pl.Name} = Microsoft.FSharp.Core.FSharpOption<{GetTypeDisplayName(pl.MemberType)}>.Some({loadVar});");
                    else
                        sb.AppendLine($"    _impl.{pl.Name} = {loadVar};");
                }
            }
            if (spec.AutoConnects.Length > 0)
            {
                foreach (var ac in spec.AutoConnects)
                {
                    var pnames = Enumerable.Range(0, ac.ParamTypes.Length).Select(i => "arg" + i).ToArray();
                    var paramDecls = string.Join(", ", ac.ParamTypes.Select(GetTypeDisplayName).Zip(pnames, (t, n) => t + " " + n));
                    var argList = string.Join(", ", pnames);
                    sb.AppendLine($"    GetNodeOrNull<Node>(new NodePath(\"{Escape(ac.Path)}\"))?.Connect(\"{Escape(ac.Signal)}\", Callable.From(({paramDecls}) => _impl.{ac.HandlerName}({argList})));".Replace("( )", "()"));
                }
            }
            sb.AppendLine("    _impl.Ready();");
            sb.AppendLine("}");
            list.Add(sb.ToString());
        }

        if (spec.HasExitTree) list.Add("public override void _ExitTree() => _impl.ExitTree();");
        if (spec.HasProcess) list.Add("public override void _Process(double delta) => _impl.Process(delta);");
        if (spec.HasPhysicsProcess) list.Add("public override void _PhysicsProcess(double delta) => _impl.PhysicsProcess(delta);");
        if (spec.HasInput) list.Add("public override void _Input(Godot.InputEvent @event) => _impl.Input(@event);");
        if (spec.HasUnhandledInput) list.Add("public override void _UnhandledInput(Godot.InputEvent @event) => _impl.UnhandledInput(@event);");
        if (spec.HasNotification) list.Add("public override void _Notification(long what) => _impl.Notification(what);");
        return list;
    }

    private static IEnumerable<string> BuildUiAndCanvasMembers(ScriptSpec spec)
    {
        bool IsControl() => spec.BaseTypeName.EndsWith(".Control", StringComparison.Ordinal);
        bool IsCanvasItem() => spec.BaseTypeName.EndsWith(".CanvasItem", StringComparison.Ordinal) || spec.BaseTypeName.EndsWith(".Node2D", StringComparison.Ordinal) || spec.BaseTypeName.EndsWith(".Control", StringComparison.Ordinal);
        var list = new List<string>();
        if (IsControl() && spec.HasGuiInput) list.Add("public override void _GuiInput(Godot.InputEvent @event) => _impl.GuiInput(@event);");
        if (IsControl() && spec.HasShortcutInput) list.Add("public override void _ShortcutInput(Godot.InputEvent @event) => _impl.ShortcutInput(@event);");
        if (IsControl() && spec.HasUnhandledKeyInput) list.Add("public override void _UnhandledKeyInput(Godot.InputEvent @event) => _impl.UnhandledKeyInput(@event);");
        if (IsCanvasItem() && spec.HasDraw) list.Add("public override void _Draw() => _impl.Draw();");
        if (IsControl() && spec.HasCanDropData) list.Add("public override bool _CanDropData(Godot.Vector2 atPosition, Godot.Variant data) => _impl.CanDropData(atPosition, data);");
        if (IsControl() && spec.HasDropData) list.Add("public override void _DropData(Godot.Vector2 atPosition, Godot.Variant data) => _impl.DropData(atPosition, data);");
        if (IsControl() && spec.HasGetDragData) list.Add("public override Godot.Variant _GetDragData(Godot.Vector2 atPosition) => (Godot.Variant)_impl.GetDragData(atPosition);");
        if (IsControl() && spec.HasHasPoint) list.Add("public override bool _HasPoint(Godot.Vector2 position) => _impl.HasPoint(position);");
        if (IsControl() && spec.HasGetMinimumSize) list.Add("public override Godot.Vector2 _GetMinimumSize() => _impl.GetMinimumSize();");
        if (IsControl() && spec.HasMakeCustomTooltip) list.Add("public override Godot.Control _MakeCustomTooltip(string forText) => _impl.MakeCustomTooltip(forText);");
        if (IsControl() && spec.HasGetTooltip) list.Add("public override string _GetTooltip(Godot.Vector2 atPosition) => _impl.GetTooltip(atPosition);");
        return list;
    }

    private static IEnumerable<string> BuildSignalMembers(ScriptSpec spec)
    {
        var list = new List<string>();
        foreach (var sig in spec.Signals)
        {
            if (sig.ParamTypes.Length == 0)
            {
                list.Add($"[Signal] public event System.Action {sig.Name};");
                list.Add($"public void Emit{sig.Name}() => {sig.Name}?.Invoke();");
            }
            else
            {
                var typeList = string.Join(", ", sig.ParamTypes.Select(GetTypeDisplayName));
                var paramDecls = string.Join(", ", sig.ParamTypes.Select(GetTypeDisplayName).Zip(sig.ParamNames, (t, n) => t + " " + n));
                var argList = string.Join(", ", sig.ParamNames);
                list.Add($"[Signal] public event System.Action<{typeList}> {sig.Name};");
                list.Add($"public void Emit{sig.Name}({paramDecls}) => {sig.Name}?.Invoke({argList});");
            }
        }
        return list;
    }
}
