using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Headsetsniper.Godot.FSharp.ShimGen;

internal static class RoslynCodeGenerator
{
    public static string Generate(ScriptSpec spec, string? fsSourceDir)
    {
        // Header trivia
        var version = GetGeneratorVersionMajorMinorPatch();
        var header = SyntaxFactory.TriviaList(
            SyntaxFactory.Comment("// <auto-generated>"), SyntaxFactory.EndOfLine("\n"),
            SyntaxFactory.Comment("// This file was generated by Headsetsniper.Godot.FSharp.ShimGen."), SyntaxFactory.EndOfLine("\n"),
            SyntaxFactory.Comment("// Do NOT edit this file manually. Any changes will be overwritten."), SyntaxFactory.EndOfLine("\n"),
            SyntaxFactory.Comment("// ShimGenVersion: " + version), SyntaxFactory.EndOfLine("\n"),
            SyntaxFactory.Comment("// Source F# type: " + (spec.ImplType.FullName ?? spec.ImplType.Name ?? "GeneratedShim")), SyntaxFactory.EndOfLine("\n"),
            // Intentionally omit SourceFile/SourceHash in the initial Roslyn scaffold to keep changes minimal.
            SyntaxFactory.Comment("// </auto-generated>"), SyntaxFactory.EndOfLine("\n"),
            SyntaxFactory.EndOfLine("\n")
        );

        // using directives
        var usings = new[]
        {
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("Godot")),
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("Headsetsniper.Godot.FSharp.Annotations"))
        };

        // namespace
        var nsDecl = SyntaxFactory.NamespaceDeclaration(SyntaxFactory.IdentifierName("Generated"))
            .WithNamespaceKeyword(
                SyntaxFactory.Token(
                    default, SyntaxKind.NamespaceKeyword, "namespace", "namespace", default))
            .NormalizeWhitespace();

        // class attributes
        var attrLists = new List<AttributeListSyntax>();
        if (spec.Tool)
        {
            attrLists.Add(SyntaxFactory.AttributeList(
                SyntaxFactory.SingletonSeparatedList(SyntaxFactory.Attribute(SyntaxFactory.IdentifierName("Tool")))));
        }
        attrLists.Add(SyntaxFactory.AttributeList(
            SyntaxFactory.SingletonSeparatedList(SyntaxFactory.Attribute(SyntaxFactory.IdentifierName("GlobalClass")))));
        if (!string.IsNullOrWhiteSpace(spec.Icon))
        {
            var iconAttr = SyntaxFactory.Attribute(SyntaxFactory.IdentifierName("Icon"))
                .WithArgumentList(
                    SyntaxFactory.AttributeArgumentList(
                        SyntaxFactory.SingletonSeparatedList(
                            SyntaxFactory.AttributeArgument(
                                SyntaxFactory.LiteralExpression(SyntaxKind.StringLiteralExpression, SyntaxFactory.Literal(spec.Icon))))));
            attrLists.Add(SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(iconAttr)));
        }

        // class declaration
        var classDecl = SyntaxFactory.ClassDeclaration(spec.ClassName)
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword), SyntaxFactory.Token(SyntaxKind.PartialKeyword))
            .WithAttributeLists(SyntaxFactory.List(attrLists))
            .WithBaseList(
                SyntaxFactory.BaseList(
                    SyntaxFactory.SingletonSeparatedList<BaseTypeSyntax>(
                        SyntaxFactory.SimpleBaseType(SyntaxFactory.ParseTypeName(spec.BaseTypeName))
                    )));

        // private readonly ImplType _impl = new ImplType();
        var implTypeName = SyntaxFactory.ParseTypeName(GetTypeDisplayName(spec.ImplType));
        var field = SyntaxFactory.FieldDeclaration(
                SyntaxFactory.VariableDeclaration(implTypeName)
                    .WithVariables(
                        SyntaxFactory.SingletonSeparatedList(
                            SyntaxFactory.VariableDeclarator(SyntaxFactory.Identifier("_impl"))
                                .WithInitializer(
                                    SyntaxFactory.EqualsValueClause(
                                        SyntaxFactory.ObjectCreationExpression(implTypeName)
                                            .WithArgumentList(SyntaxFactory.ArgumentList()))))))
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PrivateKeyword), SyntaxFactory.Token(SyntaxKind.ReadOnlyKeyword));

        classDecl = classDecl.AddMembers(field);

        nsDecl = nsDecl.AddMembers(classDecl);

        var cu = SyntaxFactory.CompilationUnit()
            .WithUsings(SyntaxFactory.List(usings))
            .AddMembers(nsDecl)
            .WithLeadingTrivia(header);

        var text = cu.NormalizeWhitespace().ToFullString();
        // Normalize line endings to LF
        text = text.Replace("\r\n", "\n");
        return text;
    }

    private static string GetGeneratorVersionMajorMinorPatch()
    {
        try
        {
            var asm = typeof(RoslynCodeGenerator).Assembly;
            var info = asm.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
            var raw = !string.IsNullOrWhiteSpace(info) ? info! : (asm.GetName().Version?.ToString() ?? "0.0.0");
            var core = raw.Split('-', '+')[0].Trim();
            var parts = core.Split('.');
            if (parts.Length >= 3)
                return string.Join('.', parts[0], parts[1], parts[2]);
            if (parts.Length == 2)
                return string.Join('.', parts[0], parts[1], "0");
            if (parts.Length == 1)
                return string.Join('.', parts[0], "0", "0");
            return "0.0.0";
        }
        catch { return "0.0.0"; }
    }

    private static string GetTypeDisplayName(Type t)
    {
        if (t.IsArray)
        {
            var elem = t.GetElementType()!;
            return GetTypeDisplayName(elem) + "[]";
        }
        if (t.IsGenericType)
        {
            var def = t.GetGenericTypeDefinition();
            var ns = def.Namespace;
            var name = def.Name;
            var backtick = name.IndexOf('`');
            if (backtick >= 0) name = name.Substring(0, backtick);
            var args = t.GetGenericArguments().Select(GetTypeDisplayName);
            var prefix = string.IsNullOrEmpty(ns) ? string.Empty : ns + ".";
            return prefix + name + "<" + string.Join(", ", args) + ">";
        }
        if (t.IsNested)
        {
            var parts = new List<string>();
            var cur = t;
            while (cur != null)
            {
                parts.Add(cur.Name);
                cur = cur.DeclaringType;
            }
            parts.Reverse();
            var ns = t.Namespace;
            var prefix = string.IsNullOrEmpty(ns) ? string.Empty : ns + ".";
            return prefix + string.Join(".", parts);
        }
        return t.FullName ?? t.Name ?? "System.Object";
    }
}
