<Project Sdk="Godot.NET.Sdk/4.5.0">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="TetrisTypes.fs" />
    <Compile Include="TetrisTickRelay.fs" />
    <Compile Include="TetrisBagPreview.fs" />
    <Compile Include="TetrisGridView.fs" />
    <Compile Include="TetrisUiBoard.fs" />
    <Compile Include="TetrisHud.fs" />
    <Compile Include="Tetris.fs" />
  <ProjectReference Include="..\Annotations\Headsetsniper.Godot.FSharp.Annotations.csproj" />
  </ItemGroup>
</Project>
